/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * Licensed under the Oculus SDK License Agreement (the "License");
 * you may not use the Oculus SDK except in compliance with the License,
 * which is provided at the time of installation or download, or which
 * otherwise accompanies this software in either electronic or hard copy form.
 *
 * You may obtain a copy of the License at
 *
 * https://developer.oculus.com/licenses/oculussdk/
 *
 * Unless required by applicable law or agreed to in writing, the Oculus SDK
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using Meta.XR.Samples;
using UnityEngine;
using static Oculus.Interaction.Locomotion.ClimbingEvent;

namespace Oculus.Interaction.Locomotion
{
    /// <summary>
    /// A <see cref="PointableElement"/> that can be used for climbing.
    /// Instead of moving the grabbed object to a pose, it will generate <see cref="ClimbingEvents"/>
    /// and route them using <see cref="ClimbingLocomotionBroadcaster"/> if found at the grab interactor
    /// source so they can be consumed by the Rig.
    /// </summary>
    [MetaCodeSample("ISDK-Locomotion")]
    public class Climbable : PointableElement
    {
        [SerializeField, Optional]
        [Tooltip("The velocity to apply to the player when they grab this Climbable.")]
        private Vector3 _slideVelocity = Vector3.zero;
        /// <summary>
        /// The velocity to apply to the player when they grab this Climbable.
        /// Use Vector3.zero to disable sliding.
        /// </summary>
        public Vector3 SlideVelocity
        {
            get => _slideVelocity;
            set => _slideVelocity = value;
        }

        [SerializeField, Optional]
        [Tooltip("The target to pull the player up to when they grab this Climbable.")]
        private Transform _pullUpTarget;
        /// <summary>
        /// The target to pull the player up to when they grab this Climbable.
        /// </summary>
        public Transform PullUpTarget
        {
            get => _pullUpTarget;
            set => _pullUpTarget = value;
        }

        [SerializeField]
        [Optional(OptionalAttribute.Flag.AutoGenerated)]
        [Tooltip("The target transform of this Climbable.")]
        private Transform _targetTransform;
        /// <summary>
        /// The target transform of this Climbable.
        /// Can be used by the locomotor to detect if the Climbable is moving.
        /// </summary>
        public Transform Transform => _targetTransform;

        [SerializeField, Optional]
        [Tooltip("The Context to use to feed ClimbingEvent decorations. If none is provided the global context will be used.")]
        private Context _context;

        public event Action<LocomotionEvent> WhenLocomotionPerformed = delegate { };

        protected override void Start()
        {
            this.BeginStart(ref _started, () => base.Start());

            if (_targetTransform == null)
            {
                _targetTransform = transform;
            }

            this.EndStart(ref _started);
        }

        protected override void PointableElementUpdated(PointerEvent evt)
        {
            switch (evt.Type)
            {
                case PointerEventType.Select:
                    StartClimb(evt);
                    break;
                case PointerEventType.Unselect:
                    StopClimb(evt);
                    break;
                case PointerEventType.Move:
                    MoveClimb(evt);
                    break;
                case PointerEventType.Cancel:
                    StopClimb(evt);
                    break;
            }

            base.PointableElementUpdated(evt);
        }

        private void StartClimb(PointerEvent evt)
        {
            if (ClimbingLocomotionBroadcaster.TryGetClimbingLocomotionBroadcaster(evt.Identifier,
                out ClimbingLocomotionBroadcaster broadcaster, _context))
            {
                broadcaster.BroadcastClimbingEvent(
                    new ClimbingEvent(ClimbingEventType.Start, this), evt.Pose);
            }
        }

        private void StopClimb(PointerEvent evt)
        {
            if (ClimbingLocomotionBroadcaster.TryGetClimbingLocomotionBroadcaster(evt.Identifier,
                out ClimbingLocomotionBroadcaster broadcaster, _context))
            {
                broadcaster.BroadcastClimbingEvent(
                    new ClimbingEvent(ClimbingEventType.End, this), evt.Pose);
            }
        }

        private void MoveClimb(PointerEvent evt)
        {
            if (ClimbingLocomotionBroadcaster.TryGetClimbingLocomotionBroadcaster(evt.Identifier,
                out ClimbingLocomotionBroadcaster broadcaster, _context))
            {
                broadcaster.BroadcastClimbingEvent(
                    new ClimbingEvent(ClimbingEventType.Move, this), evt.Pose);
            }
        }

        #region Inject

        public void InjectOptionalTargetTransform(Transform targetTransform)
        {
            _targetTransform = targetTransform;
        }

        public void InjectOptionalContext(Context context)
        {
            _context = context;
        }

        #endregion
    }
}
